config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    sessions: 'users/sessions',
                                    registrations: 'users/registrations' }
  
  resources :postcode_search, only: [:create]
  resources :places do
    resources :restaurants
  end
  
  root to: 'places#index'
  # devise_scope :user do
  get 'users/sign_up', to: 'users/registrations#new'
  get 'users/sign_in', to: 'users/sessions#new'
  #   get 'users/auth/github/callback', to: 'users/sessions#create'
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :place

  validates :name, :address, presence: true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_place
  before_action :set_restaurant, only: %i[edit update destroy]

  def index
    @restaurants = @place.restaurants
  end

  def new
    @restaurant = @place.restaurants.new
  end

  def create
    @restaurant = @place.restaurants.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = 'Restaurant has been created'
      redirect_to place_restaurants_path(@place)
    else
      render :new
    end
  end

  def update
    if @restaurant.update(restaurant_params)
    redirect_to place_restaurants_path(@place), notice: 'Restaurant has been edited'
    else
    render :edit
    end
  end

  def destroy
    @restaurant.destroy

    redirect_to place_restaurants_path(@place)
  end

  private

  def set_place
    @place = Place.find(params[:place_id])
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :place_id)
  end
end

app/views/restaurants/_form.html.erb
<%= form_with(model: [ @place, @restaurant ], local: true) do |form|  %>

  <div class="w-50">
  <div class="form-group">  
    <%= form.label :name %><br>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">   
    <%= form.label :address %><br>
    <%= form.text_field :address, class: "form-control" %>
  </div> 

  <div class="form-group"> 
    <%= form.submit 'Save', class: 'btn btn-success' %>
  </div>
  </div>
 
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant for <%= @place.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', place_restaurants_path(@place) %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<table class="table table-bordered">
  <thead class="thead-light">
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th></th>
      <th></th>
    </tr> 
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr id="restaurant_<%= restaurant.id %>">
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= link_to 'Edit', edit_place_restaurant_path(@place, restaurant) %></td>
        <td><%= link_to 'Destroy', place_restaurant_path(@place, restaurant),
            method: :delete,
            data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<a href="<%= place_path(@place) %>">
  <%= image_tag "left-arrow.svg", style: "height: 30px; color: 255, 0, 0" %>
</a> <br>
<%= link_to 'Create Restaurant', new_place_restaurant_path(@place), class: "btn btn-primary mt-3" %>

app/views/restaurants/new.html.erb
<h1>New Restaurant for <%= @place.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', place_restaurants_path(@place) %>