config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    sessions: 'users/sessions',
                                    registrations: 'users/registrations' }
  
  resources :postcode_search, only: [:create]
  resources :places do
    resources :restaurants
  end
  
  root to: 'places#index'
  # devise_scope :user do
  get 'users/sign_up', to: 'users/registrations#new'
  get 'users/sign_in', to: 'users/sessions#new'
  #   get 'users/auth/github/callback', to: 'users/sessions#create'
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :restaurants
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, except: %i[index]
  before_action :authenticate_user!

  def index
    @username = current_user.username
    @email = current_user.email
    @search = Search.new
    @user_mailer = UserMailer.new
    @results = @search.results
    @data_length = @search.data_length
    @cantons = Place.all.pluck(:canton).uniq.unshift("All") 
  end

  def update 
    if @place.update(places_params)
      redirect_to @place
    else
      render 'edit'
    end
  end


  private

  def set_place
    @place = Place.find(params[:id])
  end

  def places_params
    params.require(:place).permit(:postcode, :description)
  end
end

app/views/places/edit.html.erb
<h1>Edit Description of <%= @place.name %> </h1>

<%= form_with model: @place, local: true do |form| %>
 
  <% if @place.errors.any? %>
  <div id="error_explanation">
    <h2>
    <%= pluralize(@place.errors.count, "error") %> prohibited
    this place description from being saved:
    </h2>
    <ul>
    <% @place.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="form-group mb-0"> 
  <%= form.label :description %><br>
  <%= form.text_area :description, class: "form-control w-50 h-100" %>
  </div>

  <div class="form-group"> 
  <%= form.submit "Save", class: "btn btn-primary mt-3" %>
  </div>

  <% end %>

<a href="<%= place_path(@place) %>">
  <%= image_tag "left-arrow.svg", style: "height: 30px" %>
</a> <br>

app/views/places/index.html.erb
<h4 class="mt-3">Signed in as <%= @username.empty? ? @email : @username %> </h4>
<%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-success ml-3' %>

<% if @search.errors.any? %>
<ul>
  <% @search.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>   
  <% end %>
</ul>   
<% end %>  

<%= form_for @search, url: postcode_search_index_path, local: true do |form| %>

  <div class="d-flex justify-content-center align-items-center">
  <div class="form-group mb-0"> 
    <%= form.text_field :input, class: "form-control" %>
  </div>
  <div class="ml-3 mb-0"> 
    <%= form.select(:canton, options_for_select(@cantons, @canton ? @canton : 'All'), {}, { class: "custom-select" } ) %>
  </div>
  <%= form.submit "Search", class: 'btn btn-success ml-3' %> 
  </div>

<% end %>

<%if @results.present?%>
  <h1 class="mt-3">Results ( of <%= @data_length %> ) </h1>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>Postcode</th>
        <th>Name</th>
        <th>Canton</th>
        <th colspan="3"></th>
      </tr> 
    </thead>
    
    <tbody>
      <% @results.each do |place| %>
        <tr id="place_<%= place.id %>">
          <td><%= place.postcode %></td>
          <td><%= highlight(place.name, @input) %></td>
          <td><%= place.canton %></td>
          <td><%= link_to 'Show', place_path(place) %></td>
        </tr>
      <% end %>
    </tbody>
  </table> 
<% else %>
  <h1>Did not find any places with those values</h1>
<% end %>

app/views/places/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>PLZ:</strong>
  <%= @place.postcode %>
</p>

<p>
  <strong>Canton:</strong>
  <%= @place.canton %>
</p>

<p>
  <strong>Description:</strong><br>
  <div class="description"><%= @place.description %></div>
</p>

<%= link_to 'Back', places_path %>
<%= link_to 'Edit', edit_place_path(@place) %> <br>
<%= link_to 'Restaurants', place_restaurants_path(@place), class: "btn btn-primary" %>